### PR TITLE
Fix cycle load issue #16 

### PR DESCRIPTION
**Pull request by cprotopa**
This commit should fix the `cycle_load` model in `residential.py`, reported in #16 . However, **calibration** for these types of loads **should still be done** with the new model (updating the `cal` value in `Appliances.py`). 
Also note the model has some assumptions that could be changed, e.g. that the cycle length and delay are constant throughout the year, and that the power is the mean power assigned for that appliance (this could be sampled instead).

### CODE REVIEW

**Comment by cprotopa** [comment]
Who could review this? @bramvdh91 @SilkeVerbruggen 
Also, should I run the calibration for these changes alone, or can it be combined with calibration for the new shower cycles in pull request #17 ? @Mathadon , what's best practice here? Cause the calibration will take hours, it's easiest to only do it once...

**Comment by Mathadon** [comment]
I'm not sure what the calibration is so that's hard to answer for me. If the point of the calibration is to detect errors then I would do it individually. Otherwise you can probably do it only once.

**Comment by bramvdh91** [comment]
I can't do much in terms of reviewing, as I'm not familiar with how this part of the code works. Okay for me to just calibrate one for the two PRs.

**Comment by cprotopa** [comment]
The calibration code changes the calibration factors (`cal`) for each load type (appliance, water flow,..), in order to obtain average annual number of cycles close to the average statistics (given in the definition of each appliance). So this calibration factor influences the probability of activating each appliance. 
In fact, I just realize this `cal` value is not used in the case of cycling loads such as in this model, so the calibration will not make any difference in the result, other than provide some check. 
Thus I'd suggest this pull request could be merged, after somebody reviews it, and the calibration is done for #17 instead.

**Comment by SilkeVerbruggen** [comment]
Hi Christina, 
I reviewed your suggestion and the code seems correct.
So I think this can be merged.

**Pull request merged**
